### PR TITLE
Feature/0.1.0 beta.rr013 a/consultar becas lista

### PR DESCRIPTION
**Pull request by itschavaa**

### CODE REVIEW

**Review by soydanteprz — CHANGES_REQUESTED** [review]
e: Android-App/app/src/main/java/com/example/kotlin/robertoruizapp/framework/adapters/ScholarshipAdapter.kt:39:73 Unresolved reference: item_becas ERRORES PARA CORRER LA APP

**Comment by itschavaa** [comment]
> e: Android-App/app/src/main/java/com/example/kotlin/robertoruizapp/framework/adapters/ScholarshipAdapter.kt:39:73 Unresolved reference: item_becas ERRORES PARA CORRER LA APP

Me faltaba hacer commit de un xml nuevo

**Review by UriGOPAR — APPROVED** [review]
Nice job 👍 :)

**Review by mafeermoreno — APPROVED** [review]
It works correctly

**Review by soydanteprz — APPROVED** [review]
LGTM

**Pull request merged**
